eureka:
  instance:
    hostname: "localhost"
  client:
    eureka-server-port: 9915
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/"
    enabled: false
server:
  port: 8015
  error:
    include-binding-errors: always
    include-message: always

spring:
  application:
    name: "playqd-api-server"
  cache:
    jcache:
      provider: "org.ehcache.jsr107.EhcacheCachingProvider"
  datasource:
    url: "jdbc:mysql://localhost:8306/db_name"
    username: "root"
    password: "****"
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write_dates_as_timestamps: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: false
        show_sql: false
        enable_lazy_load_no_trans: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    enabled: true


playqd:
  workingDir: "${user.home}/.playqd"

management:
  endpoint:
    caches:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "info", "health", "caches", "metrics", "prometheus", "shutdown" ]
  info:
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true


logging:
  level:
    org.jaudiotagger.audio: ERROR
    org.jaudiotagger.tag: ERROR

    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.data: INFO
    org.springframework.web: INFO
    org.springframework.ws: INFO

    io.playqd: INFO