eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: "http://playqd-service-discovery:${eureka.client.eureka-server-port}/eureka/"
spring:
  datasource:
    url: "jdbc:mysql://host.docker.internal:8306/${spring.application.name}-docker"
playqd:
  playlists:
    winamp:
      dir: "/media/playlists/winamp"
  sources:
    - name: "All Music"
      path: "/media/music"
      watchable: false
      scanOnStart: true
  workingDir: "/.playqd"

logging:
  level:
    io.playqd: DEBUG